# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0002_auto_20180317_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='TBD', max_length=1000),
        ),
    ]
